// packages/react/src/index.tsx
import {
  type CountSnapshot,
  type PresenceConfig,
  SimplePresence,
  type TagPeak,
} from "@simple-presence/core";
import { useCallback, useEffect, useRef, useState, type RefObject } from "react";

type PresenceOptions = Omit<PresenceConfig, "tag" | "onCountChange">;

const HISTORY_POLL_INTERVAL_MS = 10_000;

export function usePresenceCount(tag: string, options: PresenceOptions): number {
  const [count, setCount] = useState<number>(0);
  const presenceRef = useRef<SimplePresence | null>(null);

  useEffect(() => {
    const presence = new SimplePresence({
      tag,
      onCountChange: setCount,
      apiUrl: options.apiUrl,
      appKey: options.appKey,
    });

    presenceRef.current = presence;
    setCount(presence.getCount());

    return () => {
      if (presenceRef.current) {
        void presenceRef.current.destroy();
        presenceRef.current = null;
      }
    };
  }, [tag, options.apiUrl, options.appKey]);

  return count;
}

export type PresenceState = {
  count: number;
  history: CountSnapshot[];
  peak: number;
  peakAt: string | null;
  refresh: () => Promise<void>;
};

export function usePresence(tag: string, options: PresenceOptions): PresenceState {
  const [count, setCount] = useState<number>(0);
  const [history, setHistory] = useState<CountSnapshot[]>([]);
  const [stats, setStats] = useState<TagPeak>({ peak: 0, peakAt: null });
  const presenceRef = useRef<SimplePresence | null>(null);

  const fetchExtras = useCallback(async () => {
    const presence = presenceRef.current;
    if (!presence) return;

    const [h, s] = await Promise.all([presence.getHistory(), presence.getStats()]);
    setHistory(h);
    setStats(s);
  }, []);

  const cancelledRef: RefObject<boolean> = useRef(false);

  useEffect(() => {
    cancelledRef.current = false;

    const presence = new SimplePresence({
      tag,
      onCountChange: setCount,
      apiUrl: options.apiUrl,
      appKey: options.appKey,
    });

    presenceRef.current = presence;
    setCount(presence.getCount());

    const timer = setTimeout(async function poll() {
      await fetchExtras();
      if (!cancelledRef.current) {
        pollTimer = setTimeout(poll, HISTORY_POLL_INTERVAL_MS);
      }
    }, 500);
    let pollTimer: ReturnType<typeof setTimeout> = timer;

    return () => {
      cancelledRef.current = true;
      clearTimeout(pollTimer);
      if (presenceRef.current) {
        void presenceRef.current.destroy();
        presenceRef.current = null;
      }
    };
  }, [tag, options.apiUrl, options.appKey, fetchExtras]);

  return {
    count,
    history,
    peak: stats.peak,
    peakAt: stats.peakAt,
    refresh: fetchExtras,
  };
}

export type { CountSnapshot, TagPeak } from "@simple-presence/core";

// packages/solid-js/src/index.tsx
import { type CountSnapshot, type PresenceConfig, SimplePresence } from "@simple-presence/core";
import { createSignal, onCleanup, onMount } from "solid-js";

type PresenceOptions = Omit<PresenceConfig, "tag" | "onCountChange">;

const HISTORY_POLL_INTERVAL_MS = 10_000;

export function createPresenceCount(
  tag: () => string,
  options: () => PresenceOptions,
): () => number {
  const [count, setCount] = createSignal(0);
  let instance: SimplePresence | undefined;

  onMount(() => {
    const opts = options();
    instance = new SimplePresence({
      tag: tag(),
      onCountChange: setCount,
      apiUrl: opts.apiUrl,
      appKey: opts.appKey,
    });
    setCount(instance.getCount());
  });

  onCleanup(() => {
    if (instance) {
      void instance.destroy();
      instance = undefined;
    }
  });

  return count;
}

export type PresenceState = {
  count: () => number;
  history: () => CountSnapshot[];
  peak: () => number;
  peakAt: () => string | null;
  refresh: () => Promise<void>;
};

export function createPresence(tag: () => string, options: () => PresenceOptions): PresenceState {
  const [count, setCount] = createSignal(0);
  const [history, setHistory] = createSignal<CountSnapshot[]>([]);
  const [peak, setPeak] = createSignal(0);
  const [peakAt, setPeakAt] = createSignal<string | null>(null);
  let instance: SimplePresence | undefined;
  let pollTimer: ReturnType<typeof setTimeout> | undefined;

  async function fetchExtras() {
    if (!instance) return;
    const [h, s] = await Promise.all([instance.getHistory(), instance.getStats()]);
    setHistory(h);
    setPeak(s.peak);
    setPeakAt(s.peakAt);
  }

  let cancelled = false;

  onMount(() => {
    const opts = options();
    instance = new SimplePresence({
      tag: tag(),
      onCountChange: setCount,
      apiUrl: opts.apiUrl,
      appKey: opts.appKey,
    });
    setCount(instance.getCount());

    pollTimer = setTimeout(async function poll() {
      await fetchExtras();
      if (!cancelled) {
        pollTimer = setTimeout(poll, HISTORY_POLL_INTERVAL_MS);
      }
    }, 500);
  });

  onCleanup(() => {
    cancelled = true;
    if (pollTimer) clearTimeout(pollTimer);
    if (instance) {
      void instance.destroy();
      instance = undefined;
    }
  });

  return {
    count,
    history,
    peak,
    peakAt,
    refresh: fetchExtras,
  };
}

export type { CountSnapshot, PresenceConfig, TagPeak } from "@simple-presence/core";
